// Code generated by MockGen. DO NOT EDIT.
// Source: xpumanager.go
//
// Generated by this command:
//
//	mockgen -source=xpumanager.go -package=xpumanager -destination=mock_xpumanager.go XPUManagerAPI
//
// Package xpumanager is a generated GoMock package.
package xpumanager

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/abyrne55/intel-gpu-operator-poc/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	controllerutil "sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
)

// MockXPUManagerAPI is a mock of XPUManagerAPI interface.
type MockXPUManagerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockXPUManagerAPIMockRecorder
}

// MockXPUManagerAPIMockRecorder is the mock recorder for MockXPUManagerAPI.
type MockXPUManagerAPIMockRecorder struct {
	mock *MockXPUManagerAPI
}

// NewMockXPUManagerAPI creates a new mock instance.
func NewMockXPUManagerAPI(ctrl *gomock.Controller) *MockXPUManagerAPI {
	mock := &MockXPUManagerAPI{ctrl: ctrl}
	mock.recorder = &MockXPUManagerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXPUManagerAPI) EXPECT() *MockXPUManagerAPIMockRecorder {
	return m.recorder
}

// EnsureXPUManagerDaemonSet mocks base method.
func (m *MockXPUManagerAPI) EnsureXPUManagerDaemonSet(ctx context.Context, devConfig *v1alpha1.DeviceConfig) (controllerutil.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureXPUManagerDaemonSet", ctx, devConfig)
	ret0, _ := ret[0].(controllerutil.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureXPUManagerDaemonSet indicates an expected call of EnsureXPUManagerDaemonSet.
func (mr *MockXPUManagerAPIMockRecorder) EnsureXPUManagerDaemonSet(ctx, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureXPUManagerDaemonSet", reflect.TypeOf((*MockXPUManagerAPI)(nil).EnsureXPUManagerDaemonSet), ctx, devConfig)
}
