// Code generated by MockGen. DO NOT EDIT.
// Source: nfd.go
//
// Generated by this command:
//
//	mockgen -source=nfd.go -package=nfd -destination=mock_nfd.go NFDRuleAPI
//
// Package nfd is a generated GoMock package.
package nfd

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/abyrne55/intel-gpu-operator-poc/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	controllerutil "sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
)

// MockNFDRuleAPI is a mock of NFDRuleAPI interface.
type MockNFDRuleAPI struct {
	ctrl     *gomock.Controller
	recorder *MockNFDRuleAPIMockRecorder
}

// MockNFDRuleAPIMockRecorder is the mock recorder for MockNFDRuleAPI.
type MockNFDRuleAPIMockRecorder struct {
	mock *MockNFDRuleAPI
}

// NewMockNFDRuleAPI creates a new mock instance.
func NewMockNFDRuleAPI(ctrl *gomock.Controller) *MockNFDRuleAPI {
	mock := &MockNFDRuleAPI{ctrl: ctrl}
	mock.recorder = &MockNFDRuleAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNFDRuleAPI) EXPECT() *MockNFDRuleAPIMockRecorder {
	return m.recorder
}

// EnsureNodeFeatureRule mocks base method.
func (m *MockNFDRuleAPI) EnsureNodeFeatureRule(ctx context.Context, devConfig *v1alpha1.DeviceConfig) (controllerutil.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNodeFeatureRule", ctx, devConfig)
	ret0, _ := ret[0].(controllerutil.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureNodeFeatureRule indicates an expected call of EnsureNodeFeatureRule.
func (mr *MockNFDRuleAPIMockRecorder) EnsureNodeFeatureRule(ctx, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNodeFeatureRule", reflect.TypeOf((*MockNFDRuleAPI)(nil).EnsureNodeFeatureRule), ctx, devConfig)
}
